version: '3.1'

services:
  java-server:
    container_name: java-server
    build: ./..
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: test-final-mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
      - ../docker/volumes/mongo:/data/db
    restart: unless-stopped

  zookeeper:
    container_name: test-final-zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    container_name: test-final-kafka
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "text_analyse_input:1:1,text_analyse_output:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
